jobs:
- job: build
  displayName: ubuntu-16.04
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - bash: conda create --yes --quiet --name test
    displayName: Create Anaconda environment

  - bash: |
      source activate test
      conda install --yes --quiet --name test python=$PYTHON_VERSION numpy scipy matplotlib cython ipython h5py
      pip install -r requirements_dev.txt
      python setup.py install
    displayName: Install requirements and build
- job: Test1
  dependsOn: build
  steps:
  - script: |
      source activate test
      export KMP_WARNINGS=0
      nosetests tests/em/static tests/seis tests/base tests/utils
    displayName: Static, Seismic, base, and utilities
- job: Test2
  dependsOn: build
  steps:
  - script: |
      source activate test
      export KMP_WARNINGS=0
      nosetests tests/flow
    displayName: Flow