parameters:
  os : ['ubuntu-16.04']
  py_vers: ['3.6','3.7']
  test: ['tests/flow','tests/em/static tests/seis tests/base tests/utils']

jobs:
  - ${{ each os in parameters.os }}:
    - ${{ each py_vers in parameters.py_vers }}:
      - ${{ each test in parameters.test }}:
        - job: 
          displayName: ${{ os }}_${{ py_vers }}_${{ test }}
          steps:
          
          - script: echo "##vso[task.prependpath]$CONDA/bin"
            displayName: Add conda to PATH
            
          - script: conda create --yes --quiet --name test
            displayName: Create Anaconda environment

          - script: |
              source activate test
              conda install --yes --quiet --name test python=${{ py_vers }} numpy scipy matplotlib cython ipython h5py
              pip install -r requirements_dev.txt
              python setup.py install
            displayName: Install requirements and build
          - script: |
              source activate test
              export KMP_WARNINGS=0
              nosetests ${{ test }}
            displayName: 'Testing ${{ test }}'
