name : Reviewdog PR Annotations
on: [pull_request_target]

jobs:
  flake8:
    runs-on: ubuntu-latest
    name: Flake8 check
    steps:
      - name: Checkout target repository source
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies to run the flake8 checks
        run: pip install -r requirements_style.txt

      - name: checkout pull request source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: 'pr_source'

      - name: flake8 review
        run: .github/workflows/scripts/reviewdog_flake8.sh
        env:
          WORKDIR: 'pr_source'
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  black:
    name: Black check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository source
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies to run the flake8 checks
        run: pip install -r requirements_style.txt

      - name: checkout pull request source
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: 'pr_source'

      - name: black review
        run: .github/workflows/scripts/reviewdog_black.sh
        env:
          WORKDIR: 'pr_source'
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}